trunk/EazyWizy/EazyWizy.WebUI/Models/CartResponseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EazyWizy.Domain.Concrete;

namespace EazyWizy.WebUI.Models
{
    public class CartResponseViewModel
    {
        public string Message { get; set; }
        public string CartTotal { get; set; }
        public int ItemCount { get; set; }
    }
}

trunk/EazyWizy/EazyWizy.WebUI/Models/ContentModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EazyWizy.Domain;
using EazyWizy.Domain.Abstract;
using EazyWizy.Domain.Entities;

namespace EazyWizy.WebUI.Models
{
    public class ContentModel
    {
        public IEnumerable<TopMenu> topMenu { get; set; }
        public LHSAllMenu lhsAllMenu { get; set; }
        public IList<LHSBrandFilter> lhsBrandFilter { get; set; }
    }
    public class LHSAllMenu
    {
        public IEnumerable<LHSMenu> lhsMenu { get; set; }
        public IEnumerable<LHSSubMenuBrand> lhsSubMenuBrand { get; set; }     
    }
}

trunk/EazyWizy/EazyWizy.WebUI/Controllers/Cart/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EazyWizy.Domain.Abstract;
using EazyWizy.Domain.Concrete;
using EazyWizy.Domain.Entities;
using EazyWizy.WebUI.Models;
using EDC = EazyWizy.Domain.Concrete;
using EazyWizy.WebUI.Utilities;

namespace EazyWizy.WebUI.Controllers.Cart
{
    public class CartController : Controller
    {
        IProductRepository repository;
        
        public CartController()
        {
            repository = new ProductRepository();
        }

        //public RedirectToRouteResult AddToCart(EDC.Cart cart, int productId, string returnUrl)
        //{
        //    Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);
        //    if (product != null)
        //    {
        //        cart.AddItem(product, 1);
        //    }

        //    return RedirectToAction("Index", new { returnUrl });
        //}
        [HttpPost]
        public ActionResult AddToCart(EDC.Cart cart, int productId, int quantity)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                cart.AddItem(product, quantity);
                var result = new CartResponseViewModel()
                {
                    Message = Server.HtmlEncode(string.Format(Constants.ADD_ITEM_TO_CART_MSG, product.Name)),
                    CartTotal = cart.ComputeTotalValue().ToString("c"),
                    ItemCount = cart.Lines.Sum(c => c.Quantity)
                };
                return Json(result);
            }
            else
                return Json(new CartResponseViewModel()
                {
                    Message = Constants.PRODUCT_CURRENTLY_UNAVAILABLE,
                    CartTotal = cart.ComputeTotalValue().ToString("c"),
                    ItemCount = cart.Lines.Sum(c => c.Quantity)
                });
        }

        //public RedirectToRouteResult RemoveFromCart(EDC.Cart cart, int productId, string returnUrl)
        //{
        //    Product product = repository.Products
        //    .FirstOrDefault(p => p.ProductId == productId);
        //    if (product != null)
        //    {
        //        cart.RemoveLine(product);
        //    }
        //    return RedirectToAction("Index", new { returnUrl });
        //}

        [HttpPost]
        public ActionResult RemoveFromCart(EDC.Cart cart, int productId)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                if (cart.Lines.Select(x => x.Product.ProductId == productId).Count() > 0)
                {
                    cart.RemoveLine(product);
                    return Json(new CartResponseViewModel()
                    {
                        Message = string.Format(Constants.REMOVE_ITEM_FROM_CART_MSG, product.Name),
                        CartTotal = cart.ComputeTotalValue().ToString("c"),
                        ItemCount = cart.Lines.Sum(c => c.Quantity)
                    });
                }
            }
            return Json(new CartResponseViewModel()
            {
                Message = string.Format(Constants.NO_PRODUCT_TO_REMOVE_MSG, product.Name),
                CartTotal = cart.ComputeTotalValue().ToString("c"),
                ItemCount = cart.Lines.Sum(c => c.Quantity)
            });
        }

        public ViewResult Index(EDC.Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public PartialViewResult Summary(EDC.Cart cart)
        {
            return PartialView(cart);
        }

        public PartialViewResult CartDetails(EDC.Cart cart)
        {
            return PartialView(cart);
        }

        public PartialViewResult CheckOutDetails(EDC.Cart cart)
        {
            return PartialView();
        }        
	}
}

trunk/EazyWizy/EazyWizy.WebUI/Controllers/CheckOut/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EazyWizy.Domain.Entities;

namespace EazyWizy.WebUI.Controllers.CheckOut
{
    public class CheckoutController : Controller
    {
        public PartialViewResult SignIn()
        {
            return PartialView();
        }
    }
}

trunk/EazyWizy/EazyWizy.WebUI/Controllers/Content/ProductDisplayController.cs
using EazyWizy.Domain.Abstract;
using EazyWizy.Domain.Concrete;
using EazyWizy.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EazyWizy.WebUI.Controllers.Content
{
    public class ContentController : Controller
    {
        private IMenuRepository menuRepository;
        public ContentController()
        {
            this.menuRepository = new EFMenuRepository();
        }
        public ActionResult ProductDisplay()
        {
            ContentModel contentModel = new ContentModel();
            contentModel.lhsBrandFilter = this.menuRepository.LHSBrandFilter;
            contentModel.lhsAllMenu = new LHSAllMenu()
            {
                lhsMenu = this.menuRepository.LHSMenu,
                lhsSubMenuBrand = this.menuRepository.LHSSubMenuBrand
            };
            return View("ProductDisplay", contentModel);
        }
	}
}

trunk/EazyWizy/EazyWizy.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using EazyWizy.Domain.Abstract;
using EazyWizy.Domain;
using EazyWizy.Domain.Concrete;
using EazyWizy.WebUI.Models;

namespace EazyWizy.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private IMenuRepository menuRepository;
        public HomeController()
        {
            this.menuRepository = new EFMenuRepository();
        }

        public ViewResult Index()
        {
            ContentModel contentModel = new ContentModel();
            contentModel.topMenu = this.menuRepository.TopMenu;       
            contentModel.lhsAllMenu = new LHSAllMenu()
            {
                lhsMenu = this.menuRepository.LHSMenu,
                lhsSubMenuBrand = this.menuRepository.LHSSubMenuBrand               
            }; 
            return View(contentModel);
        }
	}
}

trunk/EazyWizy/EazyWizy.WebUI/Controllers/Menu/LHSMenuController.cs
using EazyWizy.Domain.Abstract;
using EazyWizy.Domain.Concrete;
using EazyWizy.Domain.Entities;
using EazyWizy.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace EazyWizy.WebUI.Controllers.Menu
{
    public class LHSMenuController : Controller
    {
 
        private IMenuRepository topMenuRepository;
        public LHSMenuController()
        {
            topMenuRepository = new EFMenuRepository();
        }  
	}
}

trunk/EazyWizy/EazyWizy.WebUI/Controllers/RegisterUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EazyWizy.WebUI.Controllers
{
    public class RegisterUserController : Controller
    {
        //
        // GET: /RegisterUser/
        public ActionResult Index()
        {
            return View();
        }
	}
}

trunk/EazyWizy/EazyWizy.WebUI/Views/Cart/CartDetails.cshtml
@model EazyWizy.Domain.Concrete.Cart
           
<div id="cartDetails">
    <h2>Your Cart</h2>
    <table width="90%" align="center">

        <thead>
            <tr>
                <th align="center">Quantity</th>
                <th align="left">Item</th>
                <th align="right">Price</th>
                <th align="right">Subtotal</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.Lines)
            {
                <tr>
                    <td align="center">@line.Quantity</td>
                    <td align="left">@line.Product.product_name</td>
                    <td align="right">@line.Product.product_price</td>
                    <td align="right">
                        @((line.Quantity
                    * line.Product.product_price))
                </td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("ProductId", line.Product.product_id)
                        @*@Html.HiddenFor(x => x.ReturnUrl)*@
                        <input class="actionButtons" type="submit" value="Remove" />
                    }
                </td>
            </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" align="right">Total:</td>
                <td align="right">
                    @Model.ComputeTotalValue().ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>
    @*<p align="center" class="actionButtons">
        <a href="@Model.ReturnUrl">Continue shopping</a>
        @Html.ActionLink("Checkout now", "Checkout")
    </p>*@

</div>

trunk/EazyWizy/EazyWizy.WebUI/Views/Cart/Index.cshtml
@model EazyWizy.WebUI.Models.CartIndexViewModel

@{
    Layout = null;
    //ViewBag.Title = "Cheeckout";
}

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>EazyWizy.com</title>
        @Styles.Render("~/Content/Site/css")
        @Styles.Render("~/Content/kendo/css")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/kendo")
        @Scripts.Render("~/bundles/Site")         

    </head>
    <body>
        <div id="divRoot" style="height:600px;background-image:url(/Content/Images/WoodDivBackground.jpg);background-repeat:repeat;">
            <div id="divRootInner">
                <div id="TopMenu">
                    @Html.Partial("Menu/_PartialTopMenu")
                </div> 
                    
                <div id="accordianpanel">
                    <ul id="panelbar">
                        <li class="k-state-active">
                            Sign In
                            <div style="height:200px;">
                                @Html.Partial("../Checkout/SignIn");
                            </div>
                           
                        </li>
                        <li>
                            Address
                            <div>

                                This is address
                            </div>
                        </li>
                        <li>
                            Order Summary
                            <div>This is Order Summary</div>
                        </li>
                        <li>
                            Payments
                            <div style="height:350px;">
                                @Html.Partial("_PartialPayments")
                            </div>
                        </li>                       
                    </ul>
                </div>             
            </div>
        </div>    
        @*<script>
            $(document).ready(function () {
                var getItem = function (target) {
                    var itemIndexes = target.val().split(/[.,]/),
                        rootItem = panelBar.element.children("li").eq(itemIndexes[0]);

                    return itemIndexes.length > 1 ?
                        rootItem.find(".k-group > .k-item").eq(itemIndexes[1]) :
                        rootItem;
                },
                    select = function (e) {
                        if (e.type != "keypress" || kendo.keys.ENTER == e.keyCode)
                            panelBar.select(getItem($("#selectIndex")));
                    },
                    append = function (e) {
                        if (e.type != "keypress" || kendo.keys.ENTER == e.keyCode)
                            panelBar.append({
                                text: $("#appendText").val()
                            }, panelBar.select());
                    },
                    before = function (e) {
                        if (e.type != "keypress" || kendo.keys.ENTER == e.keyCode)
                            panelBar.insertBefore({
                                text: $("#beforeText").val()
                            }, panelBar.select());
                    },
                    after = function (e) {
                        if (e.type != "keypress" || kendo.keys.ENTER == e.keyCode)
                            panelBar.insertAfter({
                                text: $("#afterText").val()
                            }, panelBar.select());
                    };

                $(".selectItem").click(select);
                $("#selectIndex").keypress(select);

                $(".appendItem").click(append);
                $("#appendText").keypress(append);

                $(".beforeItem").click(before);
                $("#beforeText").keypress(before);

                $(".afterItem").click(after);
                $("#afterText").keypress(after);

                $(".toggleItem").click(function (e) {
                    var item = panelBar.select();
                    panelBar.enable(item, item.hasClass("k-state-disabled"));
                });

                $(".triggerItem").click(function (e) {
                    var item = panelBar.select();

                    if (item.hasClass("k-state-active")) {
                        panelBar.collapse(item);
                    } else {
                        panelBar.expand(item);
                    }
                });

                $(".removeItem").click(function (e) {
                    panelBar.remove(panelBar.select());
                });

            });

            var panelBar = $("#panelbar").kendoPanelBar().data("kendoPanelBar");
        </script>*@

        <script>
            $(document).ready(function () {
                $("#panelbar").kendoPanelBar({
                    expandMode: "single",
                    contentUrls: [
                        '../../content/web/panelbar/ajax/ajaxContent1.html',
                        '../../content/web/panelbar/ajax/ajaxContent2.html',
                        '../../content/web/panelbar/ajax/ajaxContent3.html',
                        '../../content/web/panelbar/ajax/ajaxContent4.html'
                    ]
                });
            });
        </script>
        <style scoped>
            .configuration .k-textbox {
                width: 40px;
            }
        </style>
    </body>
</html>

trunk/EazyWizy/EazyWizy.WebUI/Views/Cart/_PartialPayments.cshtml
<section id="wrapper" class="wrapper">

    <h1 class="title">Checkout</h1>

    <div id="v-nav">

        <ul>
            <li tab="tab1" class="first current">Credit/Debit Card</li>
            <li tab="tab2">Net Banking</li>
            <li tab="tab3">Cash On Delivery</li>
            <li tab="tab4" class="last">EazyWizy Coupons</li>
        </ul>

        <div class="tab-content">
            <h4>Tab 1</h4>
        </div>

        <div class="tab-content">
            <h4>Tab2</h4>
        </div>

        <div class="tab-content">
            <h4>Tab3</h4>
        </div>

        <div class="tab-content">
            <h4>Tab4</h4>
        </div>

    </div>

</section>

trunk/EazyWizy/EazyWizy.WebUI/Views/Checkout/SignIn.cshtml
<div class="signIn">
    <span id="emailAddress">Email Address</span>
    <input type="text" id="txtemailAddress" />
    <input type="checkbox" id="chkIsUser" value="EazyWizy User" />
    <div class="userSignIn non-user">
        <span id="password">Password</span>
        <input type="text" id="txtPassWord" />
        <input type="button" id="btnContinue" value="Continue" />
    </div>
    <div class="newuser-register">
        <div>
            <input type="text" id="txtnewPassword" />
            
        </div>
    </div>
</div>

trunk/EazyWizy/EazyWizy.WebUI/Views/Content/ProductDisplay.cshtml
@model EazyWizy.WebUI.Models.ContentModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>EazyWizy.com</title>
        @Styles.Render("~/Content/Site/css")    
        @Styles.Render("~/Content/kendo/css") 
        @Styles.Render("~/Content/jqueryui/css")   
        @Scripts.Render("~/bundles/jquery")  
        @Scripts.Render("~/bundles/kendo")   
        @Scripts.Render("~/bundles/Site")   
    </head>
    <body>
        <div id="divRoot">
           <div id="divRootInner">   
                <div id="TopMenu">            
                     @Html.Partial("Menu/_PartialTopMenu")               
                </div> 
                <div>                 
                    <div class="disp-Block div-lhs-filter">
                        @Html.Partial("Menu/_PartialBrandFilter",Model.lhsBrandFilter)    
                    </div> 
                </div>            

             <div class="disp-inBlock">Here the product list will be displayed</div>                        
           </div>
        </div>      
    </body>
</html>

trunk/EazyWizy/EazyWizy.WebUI/Views/Home/Index.cshtml
@model EazyWizy.WebUI.Models.ContentModel
@{
    Layout = null;
    ViewBag.Title = "Online Grocery Mall";
}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>EazyWizy.com</title>
        @Styles.Render("~/Content/Site/css")    
        @Styles.Render("~/Content/kendo/css")  
        @Scripts.Render("~/bundles/jquery")  
        @Scripts.Render("~/bundles/kendo")   
        @Scripts.Render("~/bundles/Site")   
    </head>
    <body>
        <div id="divRoot">
           <div id="divRootInner">   
             <div id="TopMenu">            
                 @Html.Partial("Menu/_PartialTopMenu")               
             </div>  
            @* <div class="disp-Block div-mid-top">                 
                 <div id="divFilters" class='ew-div-filters'></div>
             </div>*@
             <div class="disp-Block div-index-lhs">
                 @Html.Partial("Menu/_PartialLHSMenu",Model.lhsAllMenu)      
             </div>             
           </div>
        </div>      
    </body>
</html>

trunk/EazyWizy/EazyWizy.WebUI/Views/Shared/Menu/_PartialBrandFilter.cshtml
@model IList<EazyWizy.Domain.Entities.LHSBrandFilter>
<div class="ew-lhs-div-brand-filter">
    <div class="ew-lhs-brand-header-filter ew-cursor">
        <div class="ew-lhs-filter-header-font">Brands</div>
        <div class="ew-lhs-div-filterclear">
            <img src="~/Content/Images/clearFilter.ico" class="ew-lhs-filterclear-image" alt="" />
            <span style="color:lightgrey">clear</span>        
        </div>
    </div>  
    <div class="ew-lhs-div-brandlist-filter">
        <ul class="ew-lhs-ul">
            @foreach (var item in Model.ToList())
            {
                <li class='ew-lhs-filter-li ew-lhs-font'>
                    <input type="checkbox" style="cursor:inherit;" id="@item.IdBrand" />
                    <span>                   
                        @item.Name                  
                    </span>     
                </li>
            }
        </ul>
    </div>  
</div>
<div class="ew-lhs-div-rating-filter ew-lhs-filter-margin">
    @*Rating Related *@
    <div class="ew-lhs-rating-header-filter">
        <div style="display:inherit;font-size:17px">Ratings</div>
        <div class="ew-lhs-div-filterclear" style="display:inherit;float:right;cursor:pointer;margin-top:2px">
            <img src="~/Content/Images/clearFilter.ico" style="width:15px;vertical-align:middle;margin-top:-2px" alt="" />
            <span style="color:lightgrey">clear</span>         
        </div>
    </div>        
    <div class="ew-lhs-div-ratinglist-filter">
        <ul class="ew-lhs-ul">          
            <li class='ew-lhs-filter-li ew-lhs-font'>
                <input type="checkbox" style="cursor:inherit;"/>
                <span>5 Star</span>     
            </li>          
            <li class='ew-lhs-filter-li ew-lhs-font'>
                <input type="checkbox" style="cursor:inherit;"/>
                <span>4 Star</span>     
            </li>          
            <li class='ew-lhs-filter-li ew-lhs-font'>
                <input type="checkbox" style="cursor:inherit;"/>
                <span>3 Star</span>     
            </li>          
            <li class='ew-lhs-filter-li ew-lhs-font'>
                <input type="checkbox" style="cursor:inherit;"/>
                <span>2 Star</span>     
            </li>          
            <li class='ew-lhs-filter-li ew-lhs-font'>
                <input type="checkbox" style="cursor:inherit;"/>
                <span>1 Star</span>     
            </li>          
        </ul>
    </div>  
</div>

trunk/EazyWizy/EazyWizy.WebUI/Views/Shared/Menu/_PartialLHSMenu.cshtml
@model EazyWizy.WebUI.Models.LHSAllMenu
<div id="divLHSMenu" class="ew-lhs-div-border" style="width:200px;">
    <ul class="ew-lhs-ul">
        @foreach (var item in Model.lhsMenu.ToList())
        {
            <li class='ew-lhs-li ew-lhs-font'>
                <span>
                    <img class='ew-lhs-image' src='~/Content/Images/@item.Image' alt="" />
                       @item.Name
                    <span class="k-icon k-i-arrow-e ew-lhs-right-arrow"></span> 
                </span>      
                <div class='ew-lhs-subdiv'>
                    <ul class='ew-lhs-submenu-ul'>          
                         @foreach (var brandItem in Model.lhsSubMenuBrand.ToList())
                         {  
                            <li data-associated-id="@brandItem.IdBrand" class="ew-lhs-sub-li">
                                <span>
                                    <img class='ew-lhs-image' src='~/Content/Images/@brandItem.Image' alt="" />
                                        @Html.ActionLink(@brandItem.Name, "ProductDisplay", "Content")
                                </span>    
                            </li>         
                         }
                     </ul>
                </div>   
            </li>
        }
    </ul>
</div>

trunk/EazyWizy/EazyWizy.WebUI/Views/Shared/Menu/_PartialTopMenu.cshtml
<div id="divHeader1">
      <div id="divImage" class="cssHeader-Menu-font">
           @*<img src="~/Content/Images/Home.png" alt="Image"/>*@
            <span>Image</span>           
      </div>     
      <div id="divMyHome" class="cssHeader-Menu-font">
           @*<img src="~/Content/Images/Home.png" alt="Home" />*@
          <span>Home</span>         
      </div>     
      <div id="divDiscounts" class="cssHeader-Menu-font">
          @*<img src="~/Content/Images/Home.png" alt="Home" />*@
          <span>Discounts</span>         
      </div>     
      <div id="divMyAcct" class="cssHeader-Menu-font">
         @* <img src="~/Content/Images/Home.png" alt="Home" />*@
          <span>My Account</span>           
      </div>
      <div id="divLastPurchase" class="cssHeader-Menu-font">
         @* <img src="~/Content/Images/Home.png" alt="Home" />*@
          <span>Last Purchase</span>         
      </div>
      <div id="divTrackOrder" class="cssHeader-Menu-font">
          @* <img src="~/Content/Images/Register.png" alt="Track Your Order" />*@
           <span>Track Your Order</span>          
      </div>   
      <div id="divHelpSupport" class="cssHeader-Menu-font">
          @*<img src="~/Content/Images/Register.png" alt="Help & Support" />*@
          <span>Help & Support</span>         
      </div>    
      <div id="divSignIn" class="cssHeader-Menu-font">
          @*<img src="~/Content/Images/Register.png" alt="Sign In/Register" />*@
          <span>Sign In</span>         
      </div>       
      <div id="divRegister" class="cssHeader-Menu-font">
          @* <img src="~/Content/Images/Register.png" alt="Sign In/Register" />*@
          <span>Register</span>        
      </div>     

</div> 
<div id="headercart">
@*   @{Html.RenderAction("Summary", "Cart");}*@
</div>
<div id="bodycart">
    @{Html.RenderAction("CartDetails", "Cart");}
</div>
<div id="search" style="height:22px; width:418px;margin-top:-34px;margin-right:220px;position:absolute;float:right" >
    <input type="text" style="width:inherit;height:inherit" />
    
</div>